version: '2'
services:
    isa2017-app:
        image: isa2017
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://isa2017-mysql:3306/isa2017?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    isa2017-mysql:
        extends:
            file: mysql.yml
            service: isa2017-mysql
